<script type="text/javascript">
    
  //setup the function for doubleclick
  dartWallpaperRender = aetn.lib.ad.brandedCanvasRender;
    
  // Dart comes from AdManager_DoubleClick::singleton();
  document.write('<script id="ad_wall" src="http://ad.doubleclick.net/adj/<?php print $site; ?>/<?php print $zone1; ?><?php print $zone2?'/'.$zone2:''; ?>;s1=<?php print $s1; ?>;s2=<?php print $s2; ?>;pid=<?php print $pid; ?>;kw=<?php print $kw; ?>;game=<?php print $game; ?>;sweeps=<?php print $sweeps; ?>;show=<?php print $show; ?>;movie=<?php print $movie; ?>;ptype=<?php print $ptype; ?>;cat=<?php print $cat; ?>;test=<?php print ($test == 'aetn.lib.ad.testLocation()') ? "' + aetn.lib.ad.testLocation() + '" : $test; ?>;aetn=<?php print $aetn; ?><?php print $attributes?';'.$attributes:''; ?>;pos=wall;tile=' + (++Dart.tile) + (Dart.tile == 1? ';dcopt=ist': '') + ';sz=2x2;' + Dart.quantSegs + 'ord=' + Dart.ord + '?"></scr' + 'ipt>');
</script>
