<script type="text/javascript">
  // Dart comes from AdManager_DoubleClick::singleton();
  var timeintervalad_path = '<?php print $site; ?>/<?php print $zone1; ?><?php print $zone2?'/'.$zone2:''; ?>;s1=<?php print $s1; ?>;s2=<?php print $s2; ?>;pid=<?php print $pid; ?>;kw=<?php print $kw; ?>;game=<?php print $game; ?>;sweeps=<?php print $sweeps; ?>;show=<?php print $show; ?>;movie=<?php print $movie; ?>;ptype=<?php print $ptype; ?>;cat=<?php print $cat; ?>;test=<?php print ($test == 'aetn.lib.ad.testLocation()') ? "' + aetn.lib.ad.testLocation() + '" : $test; ?>;aetn=<?php print $aetn; ?><?php print $attributes?';'.$attributes:''; ?>;pos=<?php print $pos; ?>;tile=' + (++Dart.tile) + (Dart.tile == 1? ';dcopt=ist': '') + ';sz=<?php print $sz; ?>;';
</script>
<div class="timeinterval_ad_wrapper">
	<div id ="timeinterval_ad"></div>
</div>
